<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPduhwz9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPduhwz9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPduhwz9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPduhwz9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPduhwz9\appProdProjectContainer(array(
    'container.build_hash' => 'Pduhwz9',
    'container.build_id' => 'bf2ab1a8',
    'container.build_time' => 1527250562,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPduhwz9');
