<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0yfubmi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0yfubmi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0yfubmi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0yfubmi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0yfubmi\appDevDebugProjectContainer(array(
    'container.build_hash' => '0yfubmi',
    'container.build_id' => '79fa0fd4',
    'container.build_time' => 1527242692,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0yfubmi');
