<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT68uuzy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT68uuzy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT68uuzy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerT68uuzy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerT68uuzy\appDevDebugProjectContainer(array(
    'container.build_hash' => 'T68uuzy',
    'container.build_id' => 'be662bcc',
    'container.build_time' => 1527250571,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerT68uuzy');
